### ISSUE TITLE
Add ability for Warning, Tip, Important, Deprecated, and Obsolete tags everywhere you can add a Note

### ISSUE THREAD

**Issue by SarahAlphaSoftware** [BuildMan-Alpha/AlphaHelp#14]
We need to be able to mark a section in XML as a Note, Warning, Tip, Important, Deprecated, or Obsolete. 

- Must support block comments (ie, &lt;p>&lt;/p> tags).
- Must be available everywhere you can add a Note.

Coloring:

- Note - Green
- Tip - Blue
- Important - Yellow
- Warning - Red
- Deprecated - Yellow
- Obsolete - Red

**Comment by Cian-Chambliss** [comment]
Feature has been added
