### ISSUE TITLE
Change Help Generate to produce xml

### ISSUE THREAD

**Issue by SarahAlphaSoftware** [BuildMan-Alpha/AlphaHelp#7]
Add ability to produce XML output from Help Generate (or change Help Generate to produce XML instead of HTML) so we can quickly generate documentation for properties for builders, genies, etc, in Alpha.

![helpgenerate1](https://cloud.githubusercontent.com/assets/17854599/18064673/62c6f032-6dfe-11e6-92fb-682bcc2c92fe.png)

<strike>Help Generate should produce xml matching the structure of the properties. </strike>

After talking with Lachlan, Help Generate needs to generate a <page> layout for a property.

**Generating a Page for One Property**

![helpgenerate2](https://cloud.githubusercontent.com/assets/17854599/18063664/f10b9c58-6df9-11e6-9369-28905141244c.png)

For the Panel Card's "Panel card type" property, it would generate the following XML for a page:

    <page>
        <topic>Panel card type</topic>
        <description>Specify the Panel type</description>
        <sections>
            <section>
                <list>
                    <item>
                        <name-title>Option</name-title>
                        <description-title>Description</description-title>
                    </item>
                    <item>
                        <name>Default</name>
                        <description>Default value.</description>
                    </item>
                    <item>
                        <name>IFrame</name>
                        <description></description>
                    </item>
                </list>
            </section>
        </sections>
    </page>

We would like to be able to selectively choose the properties to generate the XML. 

If the interface can prompt for a folder/directory where to save the .xml documents generated from Help Generate, that would be a bonus.

Also would be nice to have: a generated index.xml page for the directory that includes the Category name for the properties and generates the  tag for the properties. For example, for the "Javascript" category in the image above, the index.xml page would be:

    <page>
        <topic>Javascript</topic>
        <description>Available Javascript Properties</description>
    
    
    </page>

The description tag content can be generated using the phrase "Available X Properties" where X is the property Category. Omit Properties if the property Category ends with the word "Properties" or "properties".

If a property name, description, or option contains a <, >, or &, the character must be enclosed inside <![CDATA[]]> tag, otherwise the XML parser will be unable to parse the document. EG:

    <description>This is the right angle bracket: <![CDATA[>]]>. Here is an ampersand: <![CDATA[&]]> </description>

**Comment by SarahAlphaSoftware** [comment]
Please include blank description tags in the List so documentation team can add a description for each property.

**Handling Default Values**
If you know in advance if a specific property is the default value - or if a default value is known and can easily be noted - include it in the description using the following format:

In the description for a <case>: "Default value is X" where X is the default value
In the description for an <item>: Default value.

**Comment by SarahAlphaSoftware** [comment]
Another example for the "Has a 'flow collapse' button" property shown in the images above:

    <page>
        <topic>Has a 'flow collapse' button</topic>
        <description>Specify if this Panel has a button that collapses or expands (i.e. 'docks' or 'hides') all Panels that are 'before' this Panel in the parent PanelLayout. The meaning of 'before' depends on the parent PanelLayout's 'flow direction'. For example, if the flow direction is LTR, then 'before' means Panels to the left of this Panel. NOTE: You only need to specify a single button - the button acts as a toggle - either collapsing or expanding Panels.</description>
    </page>

If "NOTE:" can be extracted, then the below is desired:

    <page>
        <topic>Has a 'flow collapse' button</topic>
        <description>Specify if this Panel has a button that collapses or expands (i.e. 'docks' or 'hides') all Panels that are 'before' this Panel in the parent PanelLayout. The meaning of 'before' depends on the parent PanelLayout's 'flow direction'. For example, if the flow direction is LTR, then 'before' means Panels to the left of this Panel.</description>
        <note>You only need to specify a single button - the button acts as a toggle - either collapsing or expanding Panels.</note>
    </page>

**Comment by Cian-Chambliss** [comment]
Caveat - you need to make the contents of  scripteditordebugmode.debug this:

{
   "helpgenerate" : true
}

showing HelpGenerate was disabled a while ago, so the latest build did not include it - now I condition this on the helpgenerate logical setting in the scripteditordebugmode.debug file in the EXE path.

The Create Topics In Folder hyperlink in the help generate dialog will create separate XML files for each property.
